open module gamelauncher.api {
    requires transitive com.google.gson;
    requires streamsupport;
    requires it.unimi.dsi.fastutil;
    requires de.dasbabypixel.annotations;
    requires transitive org.joml;
    requires transitive org.jetbrains.annotations;
    requires disruptor;
    requires de.dasbabypixel.property;
    requires transitive jdk.unsupported;
    requires com.google.common;

    exports gamelauncher.engine.plugin;
    exports gamelauncher.engine.game;
    exports gamelauncher.engine.data;
    exports gamelauncher.engine.network.packet;
    exports gamelauncher.engine.resource;
    exports gamelauncher.engine.util.i18n;
    exports gamelauncher.engine.util.image;
    exports gamelauncher.engine.util.logging;
    exports gamelauncher.engine.util;
    exports gamelauncher.engine.util.service;
    exports gamelauncher.engine.util.text.format;
    exports gamelauncher.engine.event.events;
    exports gamelauncher.engine.event;
    exports gamelauncher.engine.render.font;
    exports gamelauncher.engine.render;
    exports gamelauncher.engine.util.function;
    exports gamelauncher.engine.util.keybind;
    exports gamelauncher.engine.util.concurrent;
    exports gamelauncher.engine;
    exports gamelauncher.engine.network.server;
    exports gamelauncher.engine.util.property;
    exports gamelauncher.engine.network;
    exports gamelauncher.engine.settings;
    exports gamelauncher.engine.util.collections;
    exports gamelauncher.engine.gui.guis;
    exports gamelauncher.engine.render.texture;
    exports gamelauncher.engine.util.profiler;
    exports gamelauncher.engine.render.model;
    exports gamelauncher.engine.render.shader;
    exports gamelauncher.engine.render.light;
    exports gamelauncher.engine.gui;
    exports gamelauncher.engine.event.events.util.keybind;
    exports gamelauncher.engine.input;
    exports gamelauncher.engine.util.text;
    exports gamelauncher.engine.util.text.serializer;
    exports gamelauncher.engine.settings.controls;

}
